from docx import Document
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
import os
import datetime


# ==============================
# DOCX GENERATION
# ==============================
def generate_docx(data: dict, country: str, output_path: str):
    doc = Document()
    
    # Add a logo-like header or title
    title = doc.add_heading(f"{country.upper()} Customs Declaration", level=0)
    title.alignment = 1 # Center align
    
    doc.add_paragraph(f"Generated by TradeFlow AI Engine").alignment = 1
    doc.add_paragraph().add_run("_" * 50).bold = True
    
    doc.add_heading("Trade Details", level=2)
    
    # Create a table for data
    table = doc.add_table(rows=0, cols=2)
    table.style = 'Table Grid'
    
    fields = [
        ("HS Code", data.get("hs_code")),
        ("Goods Description", data.get("goods_description")),
        ("Invoice Value", f"{data.get('invoice_value', '-')} {data.get('currency', '')}"),
        ("Importer Name", data.get("importer_name")),
        ("Consignee Name", data.get("consignee_name")),
        ("Exporter Name", data.get("exporter_name")),
        ("Vessel/Flight", data.get("vessel_name")),
        ("Port of Loading", data.get("port_of_loading")),
        ("Port of Entry", data.get("arrival_port")),
        ("Net Weight", data.get("net_weight")),
        ("Gross Weight", data.get("gross_weight")),
        ("Container No", data.get("container_number")),
        ("Importer Code", data.get("importer_code")),
        ("Country of Origin", data.get("country_of_origin")),
        ("Date", data.get("date")),
    ]
    
    for label, value in fields:
        row_cells = table.add_row().cells
        row_cells[0].text = label
        row_cells[0].paragraphs[0].runs[0].bold = True
        row_cells[1].text = str(value or "-")

    doc.save(output_path)


# ==============================
# PDF GENERATION
# ==============================
def generate_pdf(data: dict, country: str, output_path: str):
    from reportlab.platypus import Table, TableStyle
    
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    elements.append(Paragraph(f"<b>{country.upper()} Customs Declaration</b>", styles["Title"]))
    elements.append(Paragraph("<center><font size=10 color=grey>Generated by TradeFlow AI Platform</font></center>", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))
    
    # Table data
    table_data = [
        [Paragraph("<b>Field</b>", styles["Normal"]), Paragraph("<b>Value</b>", styles["Normal"])]
    ]
    
    fields = [
        ("HS Code", data.get("hs_code")),
        ("Goods Description", data.get("goods_description")),
        ("Invoice Value", f"{data.get('invoice_value', '-')} {data.get('currency', '')}"),
        ("Importer Name", data.get("importer_name")),
        ("Consignee Name", data.get("consignee_name")),
        ("Exporter Name", data.get("exporter_name")),
        ("Vessel/Flight", data.get("vessel_name")),
        ("Port of Loading", data.get("port_of_loading")),
        ("Port of Entry", data.get("arrival_port")),
        ("Net Weight", data.get("net_weight")),
        ("Gross Weight", data.get("gross_weight")),
        ("Container No", data.get("container_number")),
        ("Importer Code", data.get("importer_code")),
        ("Country of Origin", data.get("country_of_origin")),
        ("Date", data.get("date")),
    ]
    
    for label, value in fields:
        table_data.append([label, str(value or "-")])
    
    # Create Table
    t = Table(table_data, colWidths=[2 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    elements.append(t)
    doc.build(elements)

def generate_challan(data: dict, output_path: str):

    doc = SimpleDocTemplate(output_path, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    header_style = ParagraphStyle(
        'ChallanHeader',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.dodgerblue,
        alignment=1,
        spaceAfter=20
    )

    # Header
    elements.append(Paragraph("OFFICIAL PAYMENT CHALLAN", header_style))
    elements.append(Paragraph(f"<center>Reference: TRADE-{os.urandom(4).hex().upper()}</center>", styles["Normal"]))
    elements.append(Paragraph(f"<center>Date: {datetime.date.today()}</center>", styles["Normal"]))
    elements.append(Spacer(1, 0.4 * inch))

    # Details
    elements.append(Paragraph(f"<b>Authority:</b> {data.get('target_country')} Customs", styles["Normal"]))
    elements.append(Spacer(1, 0.2 * inch))

    # Table Data
    table_data = [
        [Paragraph("<b>Description</b>", styles["Normal"]), Paragraph("<b>Amount / Link</b>", styles["Normal"])],
        ["Assessed Item Value", f"{data.get('original_value')} {data.get('currency')}"],
        [f"Import Duty ({data.get('duty_percentage')}%)", f"{data.get('duty_amount')} {data.get('currency')}"],
        [f"{data.get('target_country')} Tax ({data.get('tax_percentage')}%)", f"{data.get('tax_amount')} {data.get('currency')}"],
        [Paragraph("<b>TOTAL PAYABLE</b>", styles["Normal"]), Paragraph(f"<b>{data.get('total_payable')} {data.get('currency')}</b>", styles["Normal"])]
    ]

    t = Table(table_data, colWidths=[3 * inch, 3 * inch], rowHeights=0.4 * inch)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BACKGROUND', (0, -1), (-1, -1), colors.lightgrey),
    ]))

    elements.append(t)
    elements.append(Spacer(1, 0.5 * inch))
    
    # Payment Instructions
    elements.append(Paragraph("<b>Payment Instructions:</b>", styles["Heading3"]))
    instructions = [
        "1. Present this challan at any authorized central bank branch.",
        "2. Payment can also be made online via the TradeFlow Authorized Portal.",
        "3. Ensure the reference number is quoted in all transactions."
    ]
    for ins in instructions:
        elements.append(Paragraph(ins, styles["Normal"]))

    doc.build(elements)